In [71]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

%matplotlib inline

In [72]:
Customer_acqDF = pd.read_csv("D:\AnalytixLabs\Case Studies\Python Case Study\Case Study 2 - Credit Card Case Study\credit-risk-and-spending-analysis\Customer Acqusition.csv", index_col= "No")

In [73]:
RepaymentsDF = pd.read_csv("D:\AnalytixLabs\Case Studies\Python Case Study\Case Study 2 - Credit Card Case Study\credit-risk-and-spending-analysis\Repayment.csv", index_col= "SL No:")

In [74]:
spendDF = pd.read_csv("D:\AnalytixLabs\Case Studies\Python Case Study\Case Study 2 - Credit Card Case Study\credit-risk-and-spending-analysis\spend.csv", index_col = "Sl No:")

In [75]:
Customer_acqDF

    Customer  Age        City   Product     Limit Company        Segment
No
1         A1   76   BANGALORE      Gold  500000.0      C1  Self Employed
2         A2   71    CALCUTTA    Silver  100000.0      C2   Salaried_MNC
3         A3   34      COCHIN  Platimum   10000.0      C3   Salaried_Pvt
4         A4   47      BOMBAY  Platimum   10001.0      C4           Govt
5         A5   56   BANGALORE  Platimum   10002.0      C5  Normal Salary
..       ...  ...         ...       ...       ...     ...            ...
96       A96   54     CHENNAI    Silver  100000.0     C19   Salaried_Pvt
97       A97   58  TRIVANDRUM  Platimum   10000.0     C20           Govt
98       A98   51    CALCUTTA  Platimum   10001.0     C21  Normal Salary
99       A99   35    CALCUTTA  Platimum   10002.0     C22  Self Employed
100     A100   36      COCHIN    Silver  100000.0      C5   Salaried_MNC

[100 rows x 7 columns]

In [76]:
Customer_acqDF[Customer_acqDF.Age < 18] = Customer_acqDF.Age.mean()

In [77]:
Customer_acqDF

    Customer   Age        City   Product     Limit Company        Segment
No
1         A1  76.0   BANGALORE      Gold  500000.0      C1  Self Employed
2         A2  71.0    CALCUTTA    Silver  100000.0      C2   Salaried_MNC
3         A3  34.0      COCHIN  Platimum   10000.0      C3   Salaried_Pvt
4         A4  47.0      BOMBAY  Platimum   10001.0      C4           Govt
5         A5  56.0   BANGALORE  Platimum   10002.0      C5  Normal Salary
..       ...   ...         ...       ...       ...     ...            ...
96       A96  54.0     CHENNAI    Silver  100000.0     C19   Salaried_Pvt
97       A97  58.0  TRIVANDRUM  Platimum   10000.0     C20           Govt
98       A98  51.0    CALCUTTA  Platimum   10001.0     C21  Normal Salary
99       A99  35.0    CALCUTTA  Platimum   10002.0     C22  Self Employed
100     A100  36.0      COCHIN    Silver  100000.0      C5   Salaried_MNC

[100 rows x 7 columns]

In [78]:
spendDF

       Customer      Month        Type     Amount
Sl No:
1            A1  12-Jan-04   JEWELLERY  485470.80
2            A1   3-Jan-04       PETRO  410556.13
3            A1  15-Jan-04     CLOTHES   23740.46
4            A1  25-Jan-04        FOOD  484342.47
5            A1  17-Jan-05      CAMERA  369694.07
...         ...        ...         ...        ...
1496        A67   4-Feb-06  BUS TICKET  356872.73
1497        A68  25-Mar-06  BUS TICKET  204971.10
1498        A69  31-Mar-06  BUS TICKET   50449.44
1499        A70  23-Mar-06  BUS TICKET   80593.94
1500        A71  24-Mar-06  BUS TICKET  194447.62

[1500 rows x 4 columns]

In [79]:
temp_df = pd.merge(left= spendDF, right = Customer_acqDF, left_on= 'Customer', right_on='Customer',how = 'inner')

final_df = pd.merge(temp_df, RepaymentsDF, how= 'inner', on= 'Customer', suffixes=['_spend', '_Repayments' ])

In [133]:
# conversion 
final_df = final_df.convert_dtypes()
final_df.Month_spend = pd.to_datetime(final_df.Month_spend)

final_df.Month_Repayments = pd.to_datetime(final_df.Month_Repayments)

final_df['Month'] = final_df.Month_spend.dt.month

final_df['Month_Name'] = final_df.Month_spend.dt.month_name()

In [134]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35344 entries, 0 to 35343
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer           35344 non-null  string
 1   Month_spend        35344 non-null  datetime64[ns]
 2   Type               35344 non-null  string
 3   Amount_spend       35344 non-null  Float64
 4   Age                35344 non-null  Int64
 5   City               35344 non-null  string
 6   Product            35344 non-null  string
 7   Limit              35344 non-null  Int64
 8   Company            35344 non-null  string
 9   Segment            35344 non-null  string
 10  Month_Repayments   35344 non-null  datetime64[ns]
 11  Amount_Repayments  35344 non-null  Float64
 12  Month              35344 non-null  int32
 13  Month_Name         35344 non-null  object
dtypes: Float64(2), Int64(2), datetime64[ns](2), int32(1), object(1), string(6)
memory usage: 3.8+ MB

In [135]:
type(final_df)

pandas.core.frame.DataFrame

In [136]:
final_df['Amount_spend'] = final_df['Amount_spend'].where(
    final_df['Amount_spend'] <= final_df['Limit'],
    final_df['Limit'] / 2
)

In [137]:
final_df

,Customer,Month_spend,Type,Amount_spend,Age,City,Product,Limit,Company,Segment,Month_Repayments,Amount_Repayments,Month,Month_Name
0,A1,2004-01-12,JEWELLERY,485470.8,76,BANGALORE,Gold,500000,C1,Self Employed,2004-01-12,495414.75,1,January
1,A1,2004-01-12,JEWELLERY,485470.8,76,BANGALORE,Gold,500000,C1,Self Employed,2004-01-03,245899.02,1,January
2,A1,2004-01-12,JEWELLERY,485470.8,76,BANGALORE,Gold,500000,C1,Self Employed,2004-01-15,259490.06,1,January
3,A1,2004-01-12,JEWELLERY,485470.8,76,BANGALORE,Gold,500000,C1,Self Employed,2004-01-25,437555.12,1,January
4,A1,2004-01-12,JEWELLERY,485470.8,76,BANGALORE,Gold,500000,C1,Self Employed,2005-01-17,165972.88,1,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35339,A67,2006-02-04,BUS TICKET,356872.73,54,CHENNAI,Gold,500000,C29,Normal Salary,2005-05-09,55638.77,2,February
35340,A69,2006-03-31,BUS TICKET,5000.0,33,CALCUTTA,Platimum,10000,C31,Self Employed,2005-01-17,10000.0,3,March
35341,A69,2006-03-31,BUS TICKET,5000.0,33,CALCUTTA,Platimum,10000,C31,Self Employed,2006-07-11,10000.0,3,March
35342,A71,2006-03-24,BUS TICKET,5001.0,34,BOMBAY,Platimum,10002,C33,Self Employed,2005-02-01,10002.0,3,March
35343,A71,2006-03-24,BUS TICKET,5001.0,34,BOMBAY,Platimum,10002,C33,Self Employed,2004-09-13,10002.0,3,March

In [138]:
final_df['Amount_Repayments'] = final_df['Amount_Repayments'].where(final_df['Amount_Repayments'] <= final_df['Limit'], final_df['Limit'])

In [139]:
final_df

,Customer,Month_spend,Type,Amount_spend,Age,City,Product,Limit,Company,Segment,Month_Repayments,Amount_Repayments,Month,Month_Name
0,A1,2004-01-12,JEWELLERY,485470.8,76,BANGALORE,Gold,500000,C1,Self Employed,2004-01-12,495414.75,1,January
1,A1,2004-01-12,JEWELLERY,485470.8,76,BANGALORE,Gold,500000,C1,Self Employed,2004-01-03,245899.02,1,January
2,A1,2004-01-12,JEWELLERY,485470.8,76,BANGALORE,Gold,500000,C1,Self Employed,2004-01-15,259490.06,1,January
3,A1,2004-01-12,JEWELLERY,485470.8,76,BANGALORE,Gold,500000,C1,Self Employed,2004-01-25,437555.12,1,January
4,A1,2004-01-12,JEWELLERY,485470.8,76,BANGALORE,Gold,500000,C1,Self Employed,2005-01-17,165972.88,1,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35339,A67,2006-02-04,BUS TICKET,356872.73,54,CHENNAI,Gold,500000,C29,Normal Salary,2005-05-09,55638.77,2,February
35340,A69,2006-03-31,BUS TICKET,5000.0,33,CALCUTTA,Platimum,10000,C31,Self Employed,2005-01-17,10000.0,3,March
35341,A69,2006-03-31,BUS TICKET,5000.0,33,CALCUTTA,Platimum,10000,C31,Self Employed,2006-07-11,10000.0,3,March
35342,A71,2006-03-24,BUS TICKET,5001.0,34,BOMBAY,Platimum,10002,C33,Self Employed,2005-02-01,10002.0,3,March
35343,A71,2006-03-24,BUS TICKET,5001.0,34,BOMBAY,Platimum,10002,C33,Self Employed,2004-09-13,10002.0,3,March

In [140]:
len(set(final_df.Customer))

94

In [141]:
final_df

,Customer,Month_spend,Type,Amount_spend,Age,City,Product,Limit,Company,Segment,Month_Repayments,Amount_Repayments,Month,Month_Name
0,A1,2004-01-12,JEWELLERY,485470.8,76,BANGALORE,Gold,500000,C1,Self Employed,2004-01-12,495414.75,1,January
1,A1,2004-01-12,JEWELLERY,485470.8,76,BANGALORE,Gold,500000,C1,Self Employed,2004-01-03,245899.02,1,January
2,A1,2004-01-12,JEWELLERY,485470.8,76,BANGALORE,Gold,500000,C1,Self Employed,2004-01-15,259490.06,1,January
3,A1,2004-01-12,JEWELLERY,485470.8,76,BANGALORE,Gold,500000,C1,Self Employed,2004-01-25,437555.12,1,January
4,A1,2004-01-12,JEWELLERY,485470.8,76,BANGALORE,Gold,500000,C1,Self Employed,2005-01-17,165972.88,1,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35339,A67,2006-02-04,BUS TICKET,356872.73,54,CHENNAI,Gold,500000,C29,Normal Salary,2005-05-09,55638.77,2,February
35340,A69,2006-03-31,BUS TICKET,5000.0,33,CALCUTTA,Platimum,10000,C31,Self Employed,2005-01-17,10000.0,3,March
35341,A69,2006-03-31,BUS TICKET,5000.0,33,CALCUTTA,Platimum,10000,C31,Self Employed,2006-07-11,10000.0,3,March
35342,A71,2006-03-24,BUS TICKET,5001.0,34,BOMBAY,Platimum,10002,C33,Self Employed,2005-02-01,10002.0,3,March
35343,A71,2006-03-24,BUS TICKET,5001.0,34,BOMBAY,Platimum,10002,C33,Self Employed,2004-09-13,10002.0,3,March

In [142]:
len(set(final_df.Type))

15

In [143]:
(final_df.Amount_spend).mean()

np.float64(149625.83273398597)

In [144]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35344 entries, 0 to 35343
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer           35344 non-null  string
 1   Month_spend        35344 non-null  datetime64[ns]
 2   Type               35344 non-null  string
 3   Amount_spend       35344 non-null  Float64
 4   Age                35344 non-null  Int64
 5   City               35344 non-null  string
 6   Product            35344 non-null  string
 7   Limit              35344 non-null  Int64
 8   Company            35344 non-null  string
 9   Segment            35344 non-null  string
 10  Month_Repayments   35344 non-null  datetime64[ns]
 11  Amount_Repayments  35344 non-null  Float64
 12  Month              35344 non-null  int32
 13  Month_Name         35344 non-null  object
dtypes: Float64(2), Int64(2), datetime64[ns](2), int32(1), object(1), string(6)
memory usage: 3.8+ MB

In [145]:
final_df.Month_spend.dt.month_name()

0         January
1         January
2         January
3         January
4         January
           ...
35339    February
35340       March
35341       March
35342       March
35343       March
Name: Month_spend, Length: 35344, dtype: object

In [146]:
final_df.Month_Repayments

0       2004-01-12
1       2004-01-03
2       2004-01-15
3       2004-01-25
4       2005-01-17
           ...
35339   2005-05-09
35340   2005-01-17
35341   2006-07-11
35342   2005-02-01
35343   2004-09-13
Name: Month_Repayments, Length: 35344, dtype: datetime64[ns]

In [151]:
pd.pivot_table(data= final_df, values = 'Amount_spend', aggfunc= 'mean', index= 'Month_Name')

             Amount_spend
Month_Name
April       132360.314233
August      170330.831216
December    106158.689384
February    155765.423991
January     149551.393567
July        169875.012936
June        181823.582093
March       137249.034097
May         159184.545634
November     146968.62748
October     130051.807562
September   151021.024071

In [152]:
final_df.groupby('Customer').agg({'Amount_spend' : 'mean'})

           Amount_spend
Customer
A1        285705.708889
A10       213745.813889
A100            50000.0
A11       250957.093889
A12       263969.375484
...                 ...
A95            240401.5
A96            54729.66
A97              5000.0
A98              5000.5
A99              5001.0

[94 rows x 1 columns]