In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

%matplotlib inline

In [3]:
Customer_acqDF = pd.read_csv("D:\AnalytixLabs\Case Studies\Python Case Study\Case Study 2 - Credit Card Case Study\credit-risk-and-spending-analysis\Customer Acqusition.csv", index_col= "No")

In [4]:
RepaymentsDF = pd.read_csv("D:\AnalytixLabs\Case Studies\Python Case Study\Case Study 2 - Credit Card Case Study\credit-risk-and-spending-analysis\Repayment.csv", index_col= "SL No:")

In [5]:
spendDF = pd.read_csv("D:\AnalytixLabs\Case Studies\Python Case Study\Case Study 2 - Credit Card Case Study\credit-risk-and-spending-analysis\spend.csv", index_col = "Sl No:")

In [6]:
Customer_acqDF

    Customer  Age        City   Product     Limit Company        Segment
No
1         A1   76   BANGALORE      Gold  500000.0      C1  Self Employed
2         A2   71    CALCUTTA    Silver  100000.0      C2   Salaried_MNC
3         A3   34      COCHIN  Platimum   10000.0      C3   Salaried_Pvt
4         A4   47      BOMBAY  Platimum   10001.0      C4           Govt
5         A5   56   BANGALORE  Platimum   10002.0      C5  Normal Salary
..       ...  ...         ...       ...       ...     ...            ...
96       A96   54     CHENNAI    Silver  100000.0     C19   Salaried_Pvt
97       A97   58  TRIVANDRUM  Platimum   10000.0     C20           Govt
98       A98   51    CALCUTTA  Platimum   10001.0     C21  Normal Salary
99       A99   35    CALCUTTA  Platimum   10002.0     C22  Self Employed
100     A100   36      COCHIN    Silver  100000.0      C5   Salaried_MNC

[100 rows x 7 columns]

In [7]:
Customer_acqDF[Customer_acqDF.Age < 18] = Customer_acqDF.Age.mean()

In [9]:
Customer_acqDF

    Customer   Age        City   Product     Limit Company        Segment
No
1         A1  76.0   BANGALORE      Gold  500000.0      C1  Self Employed
2         A2  71.0    CALCUTTA    Silver  100000.0      C2   Salaried_MNC
3         A3  34.0      COCHIN  Platimum   10000.0      C3   Salaried_Pvt
4         A4  47.0      BOMBAY  Platimum   10001.0      C4           Govt
5         A5  56.0   BANGALORE  Platimum   10002.0      C5  Normal Salary
..       ...   ...         ...       ...       ...     ...            ...
96       A96  54.0     CHENNAI    Silver  100000.0     C19   Salaried_Pvt
97       A97  58.0  TRIVANDRUM  Platimum   10000.0     C20           Govt
98       A98  51.0    CALCUTTA  Platimum   10001.0     C21  Normal Salary
99       A99  35.0    CALCUTTA  Platimum   10002.0     C22  Self Employed
100     A100  36.0      COCHIN    Silver  100000.0      C5   Salaried_MNC

[100 rows x 7 columns]

In [8]:
spendDF

       Customer      Month        Type     Amount
Sl No:
1            A1  12-Jan-04   JEWELLERY  485470.80
2            A1   3-Jan-04       PETRO  410556.13
3            A1  15-Jan-04     CLOTHES   23740.46
4            A1  25-Jan-04        FOOD  484342.47
5            A1  17-Jan-05      CAMERA  369694.07
...         ...        ...         ...        ...
1496        A67   4-Feb-06  BUS TICKET  356872.73
1497        A68  25-Mar-06  BUS TICKET  204971.10
1498        A69  31-Mar-06  BUS TICKET   50449.44
1499        A70  23-Mar-06  BUS TICKET   80593.94
1500        A71  24-Mar-06  BUS TICKET  194447.62

[1500 rows x 4 columns]

In [18]:
temp_df = pd.merge(left= spendDF, right = Customer_acqDF, left_on= 'Customer', right_on='Customer',how = 'inner')

final_df = pd.merge(temp_df, RepaymentsDF, how= 'inner', on= 'Customer', suffixes=['_spend', '_Repayments' ])

In [35]:
final_df['Amount_spend'] = final_df['Amount_spend'].where(
    final_df['Amount_spend'] <= final_df['Limit'],
    final_df['Limit'] / 2
)

In [38]:
final_df

,Customer,Month_spend,Type,Amount_spend,Age,City,Product,Limit,Company,Segment,Month_Repayments,Amount_Repayments
0,A1,12-Jan-04,JEWELLERY,485470.80,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,12-Jan-04,495414.75
1,A1,12-Jan-04,JEWELLERY,485470.80,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,03-Jan-04,245899.02
2,A1,12-Jan-04,JEWELLERY,485470.80,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,15-Jan-04,259490.06
3,A1,12-Jan-04,JEWELLERY,485470.80,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,25-Jan-04,437555.12
4,A1,12-Jan-04,JEWELLERY,485470.80,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,17-Jan-05,165972.88
...,...,...,...,...,...,...,...,...,...,...,...,...
35339,A67,4-Feb-06,BUS TICKET,356872.73,54.0,CHENNAI,Gold,500000.0,C29,Normal Salary,09-May-05,55638.77
35340,A69,31-Mar-06,BUS TICKET,5000.00,33.0,CALCUTTA,Platimum,10000.0,C31,Self Employed,17-Jan-05,140533.08
35341,A69,31-Mar-06,BUS TICKET,5000.00,33.0,CALCUTTA,Platimum,10000.0,C31,Self Employed,11-Jul-06,247628.45
35342,A71,24-Mar-06,BUS TICKET,5001.00,34.0,BOMBAY,Platimum,10002.0,C33,Self Employed,01-Feb-05,30997.74
35343,A71,24-Mar-06,BUS TICKET,5001.00,34.0,BOMBAY,Platimum,10002.0,C33,Self Employed,13-Sep-04,56286.33

In [51]:
final_df['Amount_Repayments'] = final_df['Amount_Repayments'].where(final_df['Amount_Repayments'] <= final_df['Limit'], final_df['Limit'])

In [48]:
final_df

,Customer,Month_spend,Type,Amount_spend,Age,City,Product,Limit,Company,Segment,Month_Repayments,Amount_Repayments
0,A1,12-Jan-04,JEWELLERY,485470.80,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,12-Jan-04,495414.75
1,A1,12-Jan-04,JEWELLERY,485470.80,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,03-Jan-04,245899.02
2,A1,12-Jan-04,JEWELLERY,485470.80,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,15-Jan-04,259490.06
3,A1,12-Jan-04,JEWELLERY,485470.80,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,25-Jan-04,437555.12
4,A1,12-Jan-04,JEWELLERY,485470.80,76.0,BANGALORE,Gold,500000.0,C1,Self Employed,17-Jan-05,165972.88
...,...,...,...,...,...,...,...,...,...,...,...,...
35339,A67,4-Feb-06,BUS TICKET,356872.73,54.0,CHENNAI,Gold,500000.0,C29,Normal Salary,09-May-05,55638.77
35340,A69,31-Mar-06,BUS TICKET,5000.00,33.0,CALCUTTA,Platimum,10000.0,C31,Self Employed,17-Jan-05,10000.00
35341,A69,31-Mar-06,BUS TICKET,5000.00,33.0,CALCUTTA,Platimum,10000.0,C31,Self Employed,11-Jul-06,10000.00
35342,A71,24-Mar-06,BUS TICKET,5001.00,34.0,BOMBAY,Platimum,10002.0,C33,Self Employed,01-Feb-05,10002.00
35343,A71,24-Mar-06,BUS TICKET,5001.00,34.0,BOMBAY,Platimum,10002.0,C33,Self Employed,13-Sep-04,10002.00